---
# The main playbook to deploy the site

- hosts: hadoop_all
  roles:
   - common

- hosts: zookeeper_servers
  roles:
  - { role: zookeeper_servers }
  #- { role: zookeeper_servers, when: ha_enabled }

- hosts: qjournal_servers
  roles:
  - { role: qjournal_servers, when: ha_enabled }

- hosts: hadoop_master_primary
  roles:
  - { role: hadoop_primary }

- hosts: hadoop_master_secondary
  roles:
  - { role: hadoop_secondary, when: ha_enabled }

- hosts: hadoop_slaves
  roles:
  - { role: hadoop_slaves }

- hosts: hbase_regionservers
  roles:
  - { role: hbase }

- hosts: hive
  roles:
  - { role: hive }

